# -*- coding: utf-8 -*-
"""CS335_PythonLab1_ArmaniWright.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lD8NmnIFyonaYSsmgbNG4PddSCpU3HOl
"""

name = "Armani Wright"
age = 25
ai_course = True
print("Name:", name)
print("Age in 5 years:", age + 4)
print("Is enrolled in CS 335 course?", ai_course)

topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "AI Ethics", "Real-World Considerations"]
for i, topic in enumerate(topics, start=1):
    print(f"{i}. We will study: {topic}")

student = {"name": "Armani", "score": 95}
if student["score"] >= 95:
    grade = "A+"
elif student["score"] >= 90:
    grade = "A"
elif student["score"] >= 80:
    grade = "B"
else:
    grade = "C or below"
print(f"{student['name']} received a grade of {grade}.")


def square_number(num):
    return num ** 2
def greet_student(name):
    return f"Welcome to Armani, {name}!"
# Test
print(greet_student("Armani"))
print(f"The square of 4 is {square_number(4)}")
print(f"The square of 7 is {square_number(7)}")